title: silen | 源之于生活
name: silen
email: silenme@gmail.com
description: silen
keywords: silen
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, Thinkphp, Stackoverflow]

timezone:    PRC
encoding: "utf-8"

url: http://silen.com.cn
#url: http://127.0.0.1:4000
baseurl:  "/"
domain:    silen.com.cn
permalink:     /a/:year/:month/:title.html
paginate: 5
paginate_path: "page:num"
source_code: https://github.com/silen/silen.github.io

# Build settings
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  #enable_coderay: true

gems:
  #- jemoji
  #- rouge
  # # # - jekyll-mentions
  # - jekyll-sitemap
  #- jekyll-html-pipeline

disqus:
  id: silen

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

popular_repos: []
contribute_repos: []
api_user:
  -
    href: /a/2016/05/ihuacheng-api.html#login
    label: 登录

  -
    href: /a/2016/05/ihuacheng-api.html#register
    label: 注册

  -
    href: /a/2016/05/ihuacheng-api.html#password
    label: 修改密码

  -
    href: /a/2016/05/ihuacheng-api.html#forgetPassword
    label: 忘记密码

  -
    href: /a/2016/05/ihuacheng-api.html#sendMobile
    label: 手机验证码
  -
    href: /a/2016/05/ihuacheng-api.html#updateNickName
    label: 修改昵称

api_book:
  -
    href: /a/2016/05/ihuacheng-api.html#category
    label: 获取栏目

  -
    href: /a/2016/05/ihuacheng-api.html#book_index
    label: 获取作品列表

  -
    href: /a/2016/05/ihuacheng-api.html#show
    label: 获取单篇作品

  -
    href: /a/2016/05/ihuacheng-api.html#book_comment
    label: 作品评价

api_author:
  -
    href: /a/2016/05/ihuacheng-api.html#author_index
    label: 作者信息

  -
    href: /a/2016/05/ihuacheng-api.html#book
    label: 作者作品




